### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by billbarni** [alexabbott/firebase-cms#16]
I always get this error when trying to launch the project:

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:12614:110)
    at parseSourceFileWorker (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:12546:26)
    at Object.parseSourceFile (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:12472:26)
    at Object.createSourceFile (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:12313:29)
    at VirtualFileStats.getSourceFile (C:\Users\William\Desktop\firebase-cms\node_modules\@ngtools\webpack\src\compiler_host.js:66:35)
    at WebpackCompilerHost.getSourceFile (C:\Users\William\Desktop\firebase-cms\node_modules\@ngtools\webpack\src\compiler_host.js:242:38)
    at findSourceFile (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:70693:29)
    at processImportedModules (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:70860:25)
    at findSourceFile (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:70741:17)
    at processImportedModules (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:70860:25)
    at findSourceFile (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:70741:17)
    at args (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:70630:85)
    at getSourceFileFromReferenceWorker (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:70603:34)
    at processSourceFile (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:70630:13)
    at processRootFile (C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:70484:13)
    at C:\Users\William\Desktop\firebase-cms\node_modules\typescript\lib\typescript.js:69676:60

```

environment files are created and project is configured according to the README file.

**Comment by billbarni** [comment]
Sorry. Some other thing is affecting my build environment.
