### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by mayadi1** [alexabbott/firebase-cms#22]
addPaymentSource | TypeError: Cannot read property 'val' of undefined at exports.addPaymentSource.functions.database.ref.onWrite.event (/user_code/index.js:70:28) at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:112:27) at next (native) at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71 at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24:12) at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:82:36) at /var/tmp/worker/worker.js:728:24 at process._tickDomainCallback (internal/process/next_tick.js:135:7)
-- | --

**Comment by mayadi1** [comment]
@alexabbott

**Comment by mayadi1** [comment]
Any idea???
@alexabbott
